# Generated by Django 3.1.2 on 2020-11-15 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='business',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='businessImages'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.industry'),
        ),
    ]
