# Generated by Django 3.1.2 on 2020-11-15 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201115_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.industry'),
        ),
    ]
