# Generated by Django 3.1.2 on 2020-11-20 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201119_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.business')),
                ('short_description', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
