# Generated by Django 3.1.2 on 2020-11-20 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_posting'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='post_title',
            field=models.CharField(default='Temp Posting Title', max_length=1024),
            preserve_default=False,
        ),
    ]
