# Generated by Django 3.1.2 on 2020-11-20 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_posting_post_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posting',
            new_name='Post',
        ),
    ]
